name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/wosnxn123/android_kernel_xiaomi_pissarro-hydrogen
          kernel-branch: update-to-357
          config: pissarro_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11
          aosp-clang-version: r450784d
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
